spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: dgf19981229
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
